### ISSUE TITLE
Bug with Draconic Evolution

### ISSUE THREAD

**Issue by Shadows-of-Fire** [SpitefulFox/Avaritia#89]
Ever since DE started to implement its shields, Avaritia's +INFINITY damage sword doesn't bypass them at all. Barely a scratch on what can be up to about a 2000 point shield.

**Comment by SpitefulFox** [comment]
Yup.  Blame the Draconic Evolution author for wanting to have the biggest dick in modding.

I'm not going to get into a contest with him over this.

**Comment by Shadows-of-Fire** [comment]
Couldn't the sword just be set to hit for 2.14 billion? Not too clear on what it does right now, kinda seems like it triggers on entity hit to just do a kill command or something of the sort.

**Comment by SpitefulFox** [comment]
It DOES do a kill command on entity hit.  Draconic Evolution armor is immune to being hit, so On Hit effects don't proc.

**Comment by brandon3055** [comment]
@Shadows-of-Fire @SpitefulFox The shield system was actually designed to make powerful weapons much more effective. The issue with the "+INFINITY" damage is it only deals 2 hearts of damage and then completely bypasses the vanilla damage system to actually kill the player. 

On top of that the "kill code" doesn't even run because i cancel the damage event after applying the damage to the shield. Which is probably a good thing since i block damage that ignores the vanilla damage system so it would just spam the console with errors.

I will fix this issue from my end but i just wanted to make it clear that i did not intend to make powerful weapons like this completely useless.
